services:
  webproductos.api:
    image: webproductos.api
    build:
      context: .
      dockerfile: webProductos.Api/Dockerfile

  webproductos.api-1:
    image: webproductos.api-1
    build:
      context: .
      dockerfile: webProductos.Api/Dockerfile

